# Generated by Django 2.2.5 on 2019-09-06 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre de Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio_sug_vta', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='El precio debe ser mayor a $0')], verbose_name='Precio sugerido de Venta')),
            ],
        ),
    ]
