# Generated by Django 2.2.5 on 2019-09-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
